import type { Metadata } from "next";
import BottomNavigation from "./components/BottomNavigation";
import "./styles/globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Arif's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/images/profile-about.png", // Path to your logo in the `public` folder
    shortcut: "/images/profile-about.png",
    apple: "/images/profile-about.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-screen-md mx-auto">
          <main className="w-full mb-20">{children}</main>

          <BottomNavigation />
        </div>

        <SpeedInsights />
      </body>
    </html>
  );
}
