import type { Metadata } from "next";
import BottomNavigation from "./components/BottomNavigation";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Arif Wahyu Prasetyo's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-screen-md mx-auto">
          <main className="w-full mb-20">{children}</main>

          <BottomNavigation />
        </div>
      </body>
    </html>
  );
}
